"""Refactor Event into container model

Revision ID: 1980259728ed
Revises: 649b7ca13067
Create Date: 2026-04-14 17:57:02.431756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1980259728ed'
down_revision = '649b7ca13067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_space', sa.Integer(), nullable=True))
        batch_op.drop_column('extra')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')
        batch_op.drop_column('unit_start_time')
        batch_op.drop_column('venue_start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_start_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit_start_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('extra', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('product_space')

    # ### end Alembic commands ###
