"""Add company-client-venue relationship

Revision ID: 23be3b2c7d14
Revises: 95db8b1675ea
Create Date: 2026-03-28 19:33:59.176383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23be3b2c7d14'
down_revision = '95db8b1675ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_clients',
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], )
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('venue_client_id_fkey'), type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('venue_client_id_fkey'), 'client', ['client_id'], ['id'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('venue_clients')
    # ### end Alembic commands ###
