"""Rebuild the logisicts to a simpler version

Revision ID: 297383f5ab0e
Revises: bf336948532a
Create Date: 2026-04-30 14:25:43.512957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '297383f5ab0e'
down_revision = 'bf336948532a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event_vehicle')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('arrive_venue_time')
        batch_op.drop_column('arrive_unit_time')
        batch_op.drop_column('service_end_time')
        batch_op.drop_column('service_start_time')
        batch_op.drop_column('leave_unit_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_unit_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_start_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_end_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('arrive_unit_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('arrive_venue_time', postgresql.TIME(), autoincrement=False, nullable=True))

    op.create_table('event_vehicle',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('event_vehicle_event_id_fkey')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('event_vehicle_vehicle_id_fkey'))
    )
    op.drop_table('event_movement')
    # ### end Alembic commands ###
