"""rebuild event_staff clean

Revision ID: 30ad98595c03
Revises: 7da3c2a5b12a
Create Date: 2026-04-15 14:44:42.010880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ad98595c03'
down_revision = '7da3c2a5b12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('event_product_id', sa.Integer(), nullable=True),
    sa.Column('arrive_unit_time', sa.Time(), nullable=True),
    sa.Column('arrive_venue_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_product_id'], ['event_product.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_staff')
    # ### end Alembic commands ###
