"""add event name field if events need to be named

Revision ID: 387946f37b82
Revises: 1980259728ed
Create Date: 2026-04-14 18:19:36.286473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387946f37b82'
down_revision = '1980259728ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
