"""Add product_space and passenger_space to Vehicle

Revision ID: 3b27f182a210
Revises: 5f1c793e4189
Create Date: 2026-04-14 17:09:39.081619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b27f182a210'
down_revision = '5f1c793e4189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_staff',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'staff_id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_space', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('passenger_space', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('passenger_space')
        batch_op.drop_column('product_space')

    op.drop_table('event_staff')
    # ### end Alembic commands ###
