"""add delete cascade rules to event staff and event product on event delete

Revision ID: 50bb02f9d9e8
Revises: 947ce813011c
Create Date: 2026-04-15 13:32:45.085639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bb02f9d9e8'
down_revision = '947ce813011c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_product_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_staff_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_staff_event_id_fkey'), 'event', ['event_id'], ['id'])

    with op.batch_alter_table('event_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_product_event_id_fkey'), 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###
