"""alter staff skills model

Revision ID: 5f1c793e4189
Revises: 06ff62fcad01
Create Date: 2026-03-29 19:24:57.426496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1c793e4189'
down_revision = '06ff62fcad01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_staff')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('price')
        batch_op.drop_column('notes')
        batch_op.drop_column('active')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('age')

    op.create_table('event_staff',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('event_staff_event_id_fkey')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('event_staff_staff_id_fkey'))
    )
    # ### end Alembic commands ###
