"""Refactor event staff into model

Revision ID: 649b7ca13067
Revises: ded041263417
Create Date: 2026-04-14 17:54:55.123383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649b7ca13067'
down_revision = 'ded041263417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('event_product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('arrive_unit_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('arrive_venue_time', sa.Time(), nullable=True))
        batch_op.create_foreign_key(None, 'event_product', ['event_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('arrive_venue_time')
        batch_op.drop_column('arrive_unit_time')
        batch_op.drop_column('event_product_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
