"""add ProductSkill and Staff Skill

Revision ID: 65ff237ab772
Revises: 9ce6da007514
Create Date: 2026-03-29 17:02:47.632152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ff237ab772'
down_revision = '9ce6da007514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_extra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_extra_id'], ['product_extra.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['product_skill.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False,  server_default='0.00'))

    with op.batch_alter_table('product_extra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False,  server_default='0.00'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_extra', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price')

    op.drop_table('staff_skill')
    op.drop_table('product_skill')
    # ### end Alembic commands ###
