"""add enquiry_date to event

Revision ID: 6b7b814c4e8c
Revises: d0c264404e26
Create Date: 2026-05-05 17:03:03.837491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7b814c4e8c'
down_revision = 'd0c264404e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enquiry_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('enquiry_date')

    # ### end Alembic commands ###
