"""add delete cascade rules to event_product_extra applies if event product is deleted

Revision ID: 7da3c2a5b12a
Revises: 50bb02f9d9e8
Create Date: 2026-04-15 13:36:34.005776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da3c2a5b12a'
down_revision = '50bb02f9d9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_product_extra', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_product_extra_event_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'event_product', ['event_product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_product_extra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_product_extra_event_product_id_fkey'), 'event_product', ['event_product_id'], ['id'])

    # ### end Alembic commands ###
