"""rename EventMovemnt times to venual arrival venue pickup

Revision ID: 8eb38eaa05b4
Revises: 297383f5ab0e
Create Date: 2026-04-30 14:37:32.643045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eb38eaa05b4'
down_revision = '297383f5ab0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_arrival', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('venue_pickup', sa.Time(), nullable=True))
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.drop_column('venue_pickup')
        batch_op.drop_column('venue_arrival')

    # ### end Alembic commands ###
