"""add company id back into event table

Revision ID: 947ce813011c
Revises: 387946f37b82
Create Date: 2026-04-15 12:17:47.735252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947ce813011c'
down_revision = '387946f37b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
