"""Add company-client relationship

Revision ID: 95db8b1675ea
Revises: e0632d00ecb8
Create Date: 2026-03-28 18:56:46.303503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95db8b1675ea'
down_revision = 'e0632d00ecb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])
        batch_op.drop_column('contact_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_details', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    op.drop_table('company')
    # ### end Alembic commands ###
