"""add pick up and loadin offset to event

Revision ID: d0c264404e26
Revises: 8eb38eaa05b4
Create Date: 2026-04-30 14:40:06.127199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c264404e26'
down_revision = '8eb38eaa05b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('load_in_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pickup_offset', sa.Integer(), nullable=True))

    with op.batch_alter_table('event_movement', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('pickup_offset')
        batch_op.drop_column('load_in_offset')

    # ### end Alembic commands ###
