"""User.staff_id (1-1 link to Staff), add backref relationship

Revision ID: d5a0237165d3
Revises: 30ad98595c03
Create Date: 2026-04-16 13:15:01.914858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a0237165d3'
down_revision = '30ad98595c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['staff_id'])
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
